Repository prgrms-web-devcourse-final-project/WEB2_3_Our-Tuft_FE, pull requests merged in 2025-02, with the labels that each got.

#4 [merge / mpd253] 🎉Init: 프로젝트 초기 세팅
  .gitignore
  .vscode/settings.json
  README.md
  app/(route)/game/(games)/drawingquiz/page.tsx
  app/(route)/game/(games)/oxquiz/page.tsx
  app/(route)/game/(games)/speedquiz/page.tsx
  app/(route)/game/page.tsx
  app/(route)/lobby/page.tsx
  app/(route)/login/page.tsx
  app/(route)/room/page.tsx
  app/(route)/shop/page.tsx
  app/layout.tsx
  app/page.tsx
  app/styles/globals.css
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  tailwind.config.ts
  tsconfig.json
Labels: 🎉Init

#11 💄Style: 공통 색상 정의
  app/page.tsx
  app/styles/globals.css
Labels: 💄Style

#18 🔨 Refactor: 프로젝트 폴더구조 수정
  src/app/game/(games)/drawingquiz/page.tsx
  src/app/game/(games)/oxquiz/page.tsx
  src/app/game/(games)/speedquiz/page.tsx
  src/app/game/page.tsx
  src/app/layout.tsx
  src/app/lobby/page.tsx
  src/app/login/page.tsx
  src/app/my/page.tsx
  src/app/page.tsx
  src/app/rooms/page.tsx
  src/app/shop/page.tsx
  src/styles/globals.css
Labels: 🔨Refactor

#24 ✨Feature: 모달공통 컴포넌트, 💄 Style: 모달 강퇴, 우클릭
  package-lock.json
  package.json
  public/assets/icons/info.svg
  src/app/@modal/(.)roomsds/page.tsx
  src/app/@modal/default.tsx
  src/app/layout.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalButton.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/ModalWrapper.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsBottom/info/RoomsInfo.tsx
  src/containers/rooms/roomsMain/user/UserCard.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/DeportModal.tsx
  src/containers/rooms/roomsModal/MenuModal.tsx
  src/containers/rooms/roomsModal/ProfileModal.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/store/modalStore.ts
  src/types/modalType.ts
Labels: ✨Feat, 💄Style

#26 🔨 Refactor: 모달 전역변수 사용안하게 변경
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalButton.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/index.tsx
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsBottom/info/RoomsInfo.tsx
  src/containers/rooms/roomsMain/user/UserCard.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/DeportModal.tsx
  src/containers/rooms/roomsModal/MenuModal.tsx
  src/containers/rooms/roomsModal/ProfileModal.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/store/modalStore.ts
  src/types/modalType.ts
Labels: 🔨Refactor

#29 💄 Style: 스피드 퀴즈 UI 개발
  public/assets/icons/chat-bubble.svg
  public/assets/icons/timer.gif
  src/app/game/(games)/speedquiz/page.tsx
  src/components/Modal/ModalButton.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/ModalWrapper.tsx
  src/components/Modal/index.tsx
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/game/speedQuiz/quize/Timer.tsx
  src/containers/game/speedQuiz/quize/index.tsx
  src/containers/game/speedQuiz/quizeBottom/button/index.tsx
  src/containers/game/speedQuiz/quizeBottom/chat/index.tsx
  src/containers/game/speedQuiz/quizeBottom/index.tsx
  src/containers/game/speedQuiz/quizeMain/chatBubbleList/chatBubble.tsx
  src/containers/game/speedQuiz/quizeMain/chatBubbleList/index.tsx
  src/containers/game/speedQuiz/quizeMain/index.tsx
  src/containers/game/speedQuiz/quizeMain/userList/index.tsx
  src/containers/game/speedQuiz/quizeMain/userList/user.tsx
  src/containers/game/speedQuiz/quizeModal/LeaveGameModal.tsx
  src/containers/rooms/roomsBottom/info/RoomsInfo.tsx
  src/containers/rooms/roomsMain/user/UserCard.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/DeportModal.tsx
  src/containers/rooms/roomsModal/MenuModal.tsx
  src/containers/rooms/roomsModal/ProfileModal.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/types/modalType.ts
Labels: 💄Style

#43 💄 Style: 포인트 상점 페이지 UI 개발
  public/assets/icons/coin.svg
  public/assets/images/shopbg.png
  src/app/shop/page.tsx
  src/components/ChatBox/ChatBox.tsx
  src/components/ItemCard/ItemCard.tsx
  src/components/ShopProfile/ShopProfile.tsx
  src/containers/shop/ShopContainer.tsx
  src/containers/shop/tabs/ItemTab.tsx
  src/containers/shop/tabs/MainTab.tsx
Labels: 💄Style

#44 💄 Style: 대기실, 게임 스타일 정리 🚨 Fix: 스타일 및 자잘한 오류 수정
  src/app/layout.tsx
  src/components/LeaveGameModal/LeaveGameModal.tsx
  src/components/Modal/ModalButton.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/index.tsx
  src/components/QuizBoard/index.tsx
  src/components/RoundButton/index.tsx
  src/containers/game/oxQuize/OXMain/index.tsx
  src/containers/game/oxQuize/OXQuizeContainer.tsx
  src/containers/game/speedQuiz/quizMain/index.tsx
  src/containers/rooms/roomsFooter/index.tsx
  src/containers/rooms/roomsFooter/info/RoomActionButtons.tsx
  src/containers/rooms/roomsFooter/info/RoomsInfo.tsx
  src/containers/rooms/roomsHeader/index.tsx
  src/containers/rooms/roomsMain/index.tsx
  src/containers/rooms/roomsMain/user/UserCard.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/DeportModal.tsx
  src/containers/rooms/roomsModal/MenuModal.tsx
  src/containers/rooms/roomsModal/ProfileModal.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/types/modalType.ts
Labels: 🚨Fix, 💄Style
