Repository prgrms-web-devcourse-final-project/WEB2_3_Our-Tuft_FE, pull requests merged in 2025-03, with the labels that each got.

#50 ✨ Feature: api 공통함수
  src/components/CloseButton/CloseButton.tsx
  src/components/LeaveGameModal/LeaveGameModal.tsx
  src/components/SpeedOXFooter/index.tsx
  src/containers/game/oxQuize/OXMain/index.tsx
  src/containers/game/oxQuize/OXMain/oxButtons/index.tsx
  src/containers/game/speedQuiz/quizMain/index.tsx
  src/containers/rooms/roomsFooter/info/RoomsInfo.tsx
  src/containers/rooms/roomsHeader/index.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/service/api/defaultFetch.ts
Labels: ✨Feat

#52 ✨ Feature: 방생성 모달 porps 추가
  src/app/lobby/_components/CreateRoomModal.tsx
  src/containers/rooms/roomsFooter/info/RoomsInfo.tsx
Labels: ✨Feat

#56 ✨Feat: 포인트 상점 데이터 렌더링(수정 예정) 🚨Fix: 토큰, 새로고침 관련한 오류 수정
  src/components/ItemCard/ItemCard.tsx
  src/components/NonProtectedRoute/NonProtectedRoute.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/components/ShopProfile/ShopProfile.tsx
  src/containers/login/LoginContainer.tsx
  src/containers/shop/ShopContainer.tsx
  src/containers/shop/tabs/ItemTab.tsx
  src/containers/shop/tabs/MainTab.tsx
  src/service/api/defaultFetch.ts
  src/types/item.d.ts
Labels: ✨Feat, 🚨Fix

#57 ✨ Feature: 소켓 공통 함수
  src/app/lobby/page.tsx
  src/service/api/socketConnection.ts
Labels: ✨Feat

#62 ✨ : 방 인원 및 기타 수정
  src/app/game/(games)/oxquiz/page.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsMain/chat/Chat.tsx
  src/containers/rooms/roomsMain/index.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/types/roomType.ts
Labels: ✨Feat, 🚨Fix

#64 ✨ Feature: 로비 및 대기방 게임 병합 커밋
  public/assets/images/refresh.png
  src/app/game/(games)/CATCHMIND/page.tsx
  src/app/game/(games)/OX/page.tsx
  src/app/game/(games)/SPEED/page.tsx
  src/app/lobby/_components/Chat.tsx
  src/app/lobby/_components/CreateRoomModal.tsx
  src/app/lobby/_components/GameRoomList.tsx
  src/app/lobby/_components/PasswordModal.tsx
  src/app/lobby/page.tsx
  src/components/CloseButton/CloseButton.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/components/QuizBoard/index.tsx
  src/components/SpeedOXFooter/index.tsx
  src/components/UserCard/index.tsx
  src/containers/game/oxQuize/OXMain/index.tsx
  src/containers/game/oxQuize/OXMain/oxButtons/index.tsx
  src/containers/game/oxQuize/OXQuizeContainer.tsx
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/game/speedQuiz/quizMain/index.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsFooter/index.tsx
  src/containers/rooms/roomsFooter/info/RoomActionButtons.tsx
  src/containers/rooms/roomsFooter/info/RoomsInfo.tsx
  src/containers/rooms/roomsMain/chat/Chat.tsx
  src/containers/rooms/roomsMain/index.tsx
  src/containers/rooms/roomsMain/user/UserCard.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/MenuModal.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/service/api/defaultFetch.ts
  src/service/api/socketConnection.ts
  src/service/api/topicService.ts
  src/store/roomStore.ts
  src/store/store.ts
  src/types/quizType.ts
  src/types/roomType.ts
Labels: ✨Feat, 🎉Init, 🚨Fix

#66 ✨ : 스피드 게임 말풍선 게임 진행
  src/app/lobby/_components/Chat.tsx
  src/app/lobby/_components/CreateRoomModal.tsx
  src/components/ChatBubble/index.tsx
  src/components/CloseButton/CloseButton.tsx
  src/components/Modal/ModalContainer.tsx
  src/components/Modal/index.tsx
  src/components/QuizBoard/index.tsx
  src/components/SpeedOXFooter/index.tsx
  src/containers/game/oxQuize/OXMain/index.tsx
  src/containers/game/oxQuize/OXQuizeContainer.tsx
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/game/speedQuiz/quizMain/index.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsFooter/index.tsx
  src/containers/rooms/roomsFooter/info/RoomActionButtons.tsx
  src/containers/rooms/roomsFooter/info/RoomsInfo.tsx
  src/containers/rooms/roomsMain/chat/Chat.tsx
  src/containers/rooms/roomsMain/index.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/service/api/socketConnection.ts
  src/service/api/topicService.ts
  src/store/quizeStore.ts
  src/store/roomStore.ts
  src/types/Room.ts
  src/types/modal.ts
  src/types/quizType.ts
  src/types/quize.ts
  src/types/roomType.ts
Labels: ✨Feat

#67 ✨ : 주제모달 타입 수정
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsHeader/index.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/service/api/socketConnection.ts
  src/store/roomStore.ts
Labels: ✨Feat

#68 ✨ : 무한수정
  src/components/QuizBoard/index.tsx
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/game/speedQuiz/quizMain/index.tsx
  src/containers/rooms/RoomsContainer.tsx
  src/containers/rooms/roomsFooter/index.tsx
  src/containers/rooms/roomsMain/chat/Chat.tsx
  src/containers/rooms/roomsMain/index.tsx
Labels: ✨Feat, 🚨Fix

#71 ✨ : 스피드 퀴즈 타이머, 채팅2번오류 등
  package-lock.json
  package.json
  public/assets/audio/SellBuyMusicbgm.mp3
  src/components/Modal/ModalButton.tsx
  src/components/Modal/index.tsx
  src/components/QuizBoard/Timer.tsx
  src/components/QuizBoard/index.tsx
  src/components/SpeedOXFooter/index.tsx
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
  src/containers/rooms/roomsFooter/info/RoomActionButtons.tsx
  src/containers/rooms/roomsMain/chat/Chat.tsx
  src/containers/rooms/roomsMain/user/UserList.tsx
  src/containers/rooms/roomsModal/TopicModal.tsx
  src/service/api/socketConnection.ts
  src/service/hooks/useInitializeGame.ts
  src/store/quizeStore.ts
  src/store/roomStore.ts
  src/types/modal.ts
  src/types/quize.ts
Labels: ✨Feat, 🚨Fix

#73 ✨ Feature: 게임 종료 타이머 시간 설정
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
Labels: ✨Feat

#89 ✨ Feature: 결과화면 수정
  src/containers/game/speedQuiz/SpeedQuizContainer.tsx
Labels: ✨Feat
